name: Combine OneDrive CSVs

on:
  workflow_dispatch:

jobs:
  combine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install pandas requests msal

      - name: Download from OneDrive
        env:
          ONEDRIVE_CLIENT_ID: ${{ secrets.ONEDRIVE_CLIENT_ID }}
          ONEDRIVE_CLIENT_SECRET: ${{ secrets.ONEDRIVE_CLIENT_SECRET }}
        run: python scripts/download_onedrive.py

      - name: Combine CSV files
        run: python scripts/combine_csv.py

      - name: Upload combined file to OneDrive
        env:
          ONEDRIVE_CLIENT_ID: ${{ secrets.ONEDRIVE_CLIENT_ID }}
          ONEDRIVE_CLIENT_SECRET: ${{ secrets.ONEDRIVE_CLIENT_SECRET }}
        run: python scripts/upload_onedrive.py
